default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: elastic_development

test:
  <<: *default
  database: elastic_test

production:
  <<: *default
  database: textelasticsearch
